2020-02-26 13:47:29.5073  FATAL (Program.cs:36) System.AggregateException: One or more errors occurred. (Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')) (Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray'))
 ---> System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   at System.Collections.Generic.Queue`1.Enqueue(T item)
   at Sining.Actor`1.Post(Action`1 action, STaskCompletionSource tcs) in /Users/sining/Code/Sining/Server/Core/Base/Actor/Actor.cs:line 38
   at Sining.Actor`1.AwaitPost(Action`1 action) in /Users/sining/Code/Sining/Server/Core/Base/Actor/Actor.cs:line 26
   at Sining.Program.<>c__DisplayClass1_0.<Main>b__0() in /Users/sining/Code/Sining/Server/App/Program.cs:line 33
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Sining.Program.Main(String[] args) in /Users/sining/Code/Sining/Server/App/Program.cs:line 36
 ---> (Inner Exception #1) System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   at System.Collections.Generic.Queue`1.Enqueue(T item)
   at Sining.Actor`1.Post(Action`1 action, STaskCompletionSource tcs) in /Users/sining/Code/Sining/Server/Core/Base/Actor/Actor.cs:line 38
   at Sining.Actor`1.AwaitPost(Action`1 action) in /Users/sining/Code/Sining/Server/Core/Base/Actor/Actor.cs:line 26
   at Sining.Program.<>c__DisplayClass1_0.<Main>b__0() in /Users/sining/Code/Sining/Server/App/Program.cs:line 33
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---

2020-02-26 13:50:25.4478  FATAL (Program.cs:53) System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray'))
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sining.Actor`1.Start() in /Users/sining/Code/Sining/Server/Core/Base/Actor/Actor.cs:line 50
   at Sining.Actor`1.Post(Action`1 action, STaskCompletionSource tcs) in /Users/sining/Code/Sining/Server/Core/Base/Actor/Actor.cs:line 39
   at Sining.Actor`1.AwaitPost(Action`1 action) in /Users/sining/Code/Sining/Server/Core/Base/Actor/Actor.cs:line 26
   at Sining.Program.<>c__DisplayClass1_0.<Main>b__0() in /Users/sining/Code/Sining/Server/App/Program.cs:line 41
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Sining.Program.Main(String[] args) in /Users/sining/Code/Sining/Server/App/Program.cs:line 53
 ---> (Inner Exception #1) System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   at System.Collections.Generic.Queue`1.Enqueue(T item)
   at Sining.Actor`1.Post(Action`1 action, STaskCompletionSource tcs) in /Users/sining/Code/Sining/Server/Core/Base/Actor/Actor.cs:line 38
   at Sining.Actor`1.AwaitPost(Action`1 action) in /Users/sining/Code/Sining/Server/Core/Base/Actor/Actor.cs:line 26
   at Sining.Program.<>c__DisplayClass1_0.<Main>b__0() in /Users/sining/Code/Sining/Server/App/Program.cs:line 41
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---

